---
name: setup-tektoncd-cli
description: |
  Installs the Tekton CLI (tkn)
branding:
  color: blue
  icon: anchor
inputs:
  version:
    description: |
      Tekton CLI release version
    default: latest
    required: false
  github_token:
    description: |
      GitHub token for API requests. Prevents rate-limiting when fetching release
      information. Defaults to the built-in GITHUB_TOKEN.
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    # pre-flight checks, making sure the dependencies are met
    - shell: bash
      run: ${{ github.action_path }}/probe.sh

    # installs the pre-compiled Tekton CLI
    - shell: bash
      env:
        INPUT_VERSION: ${{ inputs.version }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: sudo --preserve-env ${{ github.action_path }}/install-cli.sh
