---
name: use-setup-tektoncd-action

permissions:
  contents: read

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '*.md'

jobs:
  use-action:
    runs-on: ubuntu-latest
    steps:
      # preparing the Kubernetes cluster# (KinD) and installing kubectl
      - uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
        with:
          cluster_name: kind
          wait: 120s
      # checking out the project code on the current workspace
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      # self loading the action.yaml definitions, making possible to run the action defined on this
      # project directly
      - uses: ./setup-tektoncd/
        with:
          pipeline_version: latest
          feature_flags: '{ "enable-custom-tasks": "true" }'
          cli_version: latest

      # assert the changes performed by this action
      - shell: bash
        run: |
          ./setup-tektoncd/assert.sh
